<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="com/tagic/gc/cpm/xslt/CPMReqResLog.map" md5sum="f086039bdcdcef758b9b28740fcfabc8" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		CPMReqResLog.map
*   Map declaration(s):	CPMReqResLog
*   Input file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-GcCpm%257DcpmSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-AuditLibrary%252FAuditLoggingServices%257DupsertServiceLogResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FImpl-GcCpm%257DcpmSharedBO/message%3D%257Bhttp%253A%252F%252FImpl-AuditLibrary%252FAuditLoggingServices%257DupsertServiceLogResponseMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xltxe="http://www.ibm.com/xmlns/prod/xltxe-j"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io6="http://Impl-AuditLibrary/AuditLoggingServices"
    xmlns:io9="http://Impl-GcCpm"
    xmlns:io8="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io10="http://NBHD"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:io3="wsdl.http://Impl-AuditLibrary/AuditLoggingServices"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:MapUtils="com.ibm.wbiserver.transform.util.MapUtils"
    xmlns:map="http://Impl-GcCpm/com/tagic/gc/cpm/xslt/CPMReqResLog"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set fn math MapUtils map xltxe msl"
    version="2.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>
  <xltxe:java-extension prefix="MapUtils" class="com.ibm.wbiserver.transform.util.MapUtils"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io5:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:CPMReqResLog2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io5:smo" mode="map:CPMReqResLog"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template match="io5:smo"  mode="map:CPMReqResLog">
    <io5:smo>
      <context>
        <shared>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io9:cpmSharedBO'"/>
          </xsl:attribute>
          <!-- a simple data mapping: "body/io6:upsertServiceLogResponse/serviceLogResponse/io10:serviceLogId"(string) to "auditPrimaryKey"(int) -->
          <xsl:if test="body/io6:upsertServiceLogResponse/serviceLogResponse/io10:serviceLogId">
            <xsl:element name="auditPrimaryKey">
              <!-- variables for custom code -->
              <xsl:variable name="serviceLogId" select="body/io6:upsertServiceLogResponse/serviceLogResponse/io10:serviceLogId"/>
              <xsl:value-of select="MapUtils:stringToInt($serviceLogId, '0')"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "context/shared/itTicketNumber"(string) to "itTicketNumber"(string) -->
          <xsl:if test="context/shared/itTicketNumber">
            <xsl:element name="itTicketNumber">
              <xsl:value-of select="context/shared/itTicketNumber"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "context/shared/loggingModule"(string) to "loggingModule"(string) -->
          <xsl:if test="context/shared/loggingModule">
            <xsl:element name="loggingModule">
              <xsl:value-of select="context/shared/loggingModule"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "context/shared/traceLog"(string) to "traceLog"(string) -->
          <xsl:if test="context/shared/traceLog">
            <xsl:element name="traceLog">
              <xsl:value-of select="context/shared/traceLog"/>
            </xsl:element>
          </xsl:if>
        </shared>
      </context>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io3:upsertServiceLogResponseMsg'"/>
        </xsl:attribute>
        <io6:upsertServiceLogResponse>
          <!-- a structural mapping: "body/io6:upsertServiceLogResponse/serviceLogResponse"(ServiceLogDetailsBO) to "serviceLogResponse"(ServiceLogDetailsBO) -->
          <xsl:copy-of select="body/io6:upsertServiceLogResponse/serviceLogResponse" copy-namespaces="yes"/>
        </io6:upsertServiceLogResponse>
      </body>
    </io5:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template name="map:CPMReqResLog2">
    <xsl:param name="smo"/>
    <context>
      <shared>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io9:cpmSharedBO'"/>
        </xsl:attribute>
        <!-- a simple data mapping: "$smo/body/io6:upsertServiceLogResponse/serviceLogResponse/io10:serviceLogId"(string) to "auditPrimaryKey"(int) -->
        <xsl:if test="$smo/body/io6:upsertServiceLogResponse/serviceLogResponse/io10:serviceLogId">
          <xsl:element name="auditPrimaryKey">
            <!-- variables for custom code -->
            <xsl:variable name="serviceLogId" select="$smo/body/io6:upsertServiceLogResponse/serviceLogResponse/io10:serviceLogId"/>
            <xsl:value-of select="MapUtils:stringToInt($serviceLogId, '0')"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/shared/itTicketNumber"(string) to "itTicketNumber"(string) -->
        <xsl:if test="$smo/context/shared/itTicketNumber">
          <xsl:element name="itTicketNumber">
            <xsl:value-of select="$smo/context/shared/itTicketNumber"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/shared/loggingModule"(string) to "loggingModule"(string) -->
        <xsl:if test="$smo/context/shared/loggingModule">
          <xsl:element name="loggingModule">
            <xsl:value-of select="$smo/context/shared/loggingModule"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/shared/traceLog"(string) to "traceLog"(string) -->
        <xsl:if test="$smo/context/shared/traceLog">
          <xsl:element name="traceLog">
            <xsl:value-of select="$smo/context/shared/traceLog"/>
          </xsl:element>
        </xsl:if>
      </shared>
    </context>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'io3:upsertServiceLogResponseMsg'"/>
      </xsl:attribute>
      <io6:upsertServiceLogResponse>
        <!-- a structural mapping: "$smo/body/io6:upsertServiceLogResponse/serviceLogResponse"(ServiceLogDetailsBO) to "serviceLogResponse"(ServiceLogDetailsBO) -->
        <xsl:copy-of select="$smo/body/io6:upsertServiceLogResponse/serviceLogResponse" copy-namespaces="yes"/>
      </io6:upsertServiceLogResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::node()[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
